[package]
name = "lava"
version = "0.0.4"
edition = "2024"

[lints.rust]
dead_code = "allow"

[dependencies]
anyhow = "1"

cpal = "0"

glam = { version = "0", features = ["serde"] }
image = "0"

vulkano = { git = "https://github.com/vulkano-rs/vulkano", branch = "master", package = "vulkano" }
vulkano-macros = { git = "https://github.com/vulkano-rs/vulkano", branch = "master", package = "vulkano-macros" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano", branch = "master", package = "vulkano-shaders" }
vulkano-util = { git = "https://github.com/vulkano-rs/vulkano", branch = "master", package = "vulkano-util" }
vulkano-taskgraph = { git = "https://github.com/vulkano-rs/vulkano", branch = "master", package = "vulkano-taskgraph" }
winit = { version = "0", features = ["serde"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
jsonc = "0"
