[package]
name = "lava"
version = "0.0.4"
edition = "2024"

[lints.rust]
dead_code = "allow"

[dependencies]
anyhow = "1"

cpal = "0"

glam = { version = "0", features = ["serde"] }
image = "0"

vulkano = {version = "0", features = ["serde"]}
vulkano-macros = "0"
vulkano-shaders = "0"
vulkano-util = "0"
vulkano-taskgraph = "0"
winit = { version = "0", features = ["serde"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
jsonc = "0"
