pub mod app;
pub mod buffers;
pub mod debug;
pub mod device;
pub mod geometry;
pub mod global_parameters;
pub mod group_targets;
pub mod image_parameters;
pub mod instance;
pub mod material;
pub mod material_parameters;
pub mod math;
pub mod model;
pub mod parameters;
pub mod pipeline;
pub mod render_context;
pub mod render_graph;
pub mod render_nodes;
pub mod sampled_image;
pub mod scene_data;
pub mod scene_element;
pub mod scene_upload;
pub mod shaders;
pub mod storage_buffers;
pub mod tasks;
pub mod transform;
pub mod vertex_buffer;
pub mod window;

pub const MAX_FRAMES_IN_FLIGHT: u32 = 2;
pub const MIN_SWAPCHAIN_IMAGES: u32 = MAX_FRAMES_IN_FLIGHT + 1;
